#!/bin/bash
#support gradle,maven,ant,docker,kubernetes,pipeline,git,svn,gitlab,github,shell,email....disk,workspace....and so on
pluginsdir=`pwd`/all-jenkins-plugins
yes | cp $pluginsdir/bouncycastle-api.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/structs.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/workflow-step-api.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/workflow-scm-step.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/credentials.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/ssh-credentials.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/git-client.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/scm-api.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/junit.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/display-url-api.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/mailer.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/script-security.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/matrix-project.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/git.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/gitlab-plugin.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/github-api.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/token-macro.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/plain-credentials.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/github.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/git-server.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/javadoc.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/maven-plugin.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/pam-auth.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/windows-slaves.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/mapdb-api.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/subversion.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/ldap.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/external-monitor-job.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/icon-shim.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/matrix-auth.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/antisamy-markup-formatter.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/svn-workspace-cleaner.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/svn-revert-plugin.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/svn-tag.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/jquery-detached.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/workflow-api.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/workflow-support.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/pipeline-input-step.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/ace-editor.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/workflow-yes | cps.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/pipeline-stage-step.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/workflow-job.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/pipeline-graph-analysis.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/pipeline-rest-api.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/handlebars.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/momentjs.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/pipeline-stage-view.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/pipeline-build-step.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/cloudbees-folder.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/workflow-yes | cps-global-lib.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/branch-api.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/workflow-multibranch.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/durable-task.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/workflow-durable-task-step.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/workflow-basic-steps.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/workflow-aggregator.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/authentication-tokens.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/docker-commons.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/docker-build-step.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/ssh-slaves.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/docker-plugin.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/kubernetes.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/docker-slaves.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/disk-usage.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/diskcheck.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/ant.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/config-file-provider.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/ivy.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/ws-cleanup.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/python.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/ruby-runtime.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/pyenv.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/email-ext.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/emailext-template.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/email-ext-recipients-column.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/role-strategy.hpi $JENKINS_HOME/plugins/
yes | cp $pluginsdir/sounds.hpi $JENKINS_HOME/plugins/
